### ISSUE TITLE
Download Save File from Data page broken in Safari

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio-app#4]
The expected warning appears saying "Unfortunately, because of compatibility issues with Safari, the save file will download as a file with name 'Unknown'." But then a warning pops up asking if I'm sure I want to leave the page. That's new. I don't want to leave the page.

**Comment by cncoleman** [comment]
Even if I agree to leave the page, download does not happen. It doesn't happen from a view page either.

**Comment by esjewett** [comment]
I noticed this as well yesterday. I believe I heard something about Safari changing its approach to downloads (again!) in the latest release. Will see if I can figure it out.

**Comment by esjewett** [comment]
Will push to the site shortly. This will pick up the save-file-slimming changes as well.

**Comment by esjewett** [comment]
Version 1.2.5 is now on the main site. Release notes are here: https://github.com/humanitiesplusdesign/palladio-app/releases/tag/1.2.6
