### ISSUE TITLE
Map Tiles are not loading

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio-app#6]
Do you think this is just another expired subscription? Or is there some incompatibility?

**Comment by esjewett** [comment]
Looks like our access token expired. Not sure of the exact reason. @cncoleman, can you send me the credentials for the Mapbox account for hdlab offline and I will take a look?

<img width="551" alt="screen shot 2016-12-31 at 11 33 40 am" src="https://cloud.githubusercontent.com/assets/4822/21578627/51d8a15c-cf4d-11e6-93f6-416224a68caa.png">
